### ISSUE TITLE
Roadmap to a stable release?

### ISSUE THREAD

**Issue by brahmlower** [kyrylo/airbrake-rust#15]
The readme recommends against using this project in production until it reaches 1.0. Is there a roadmap or list of remaining work needed before a stable 1.0 release can be cut?

**Comment by kyrylo** [comment]
Hey! This project needs maintainers/developers 😄

**Comment by brahmlower** [comment]
Gotcha- I spent some time working with this source last night and feel like I've got the hang of it. I'd be interested in maintaining the project and driving toward a stable release, if that's cool with you

**Comment by kyrylo** [comment]
Thanks! I made you a collaborator.

**Comment by brahmlower** [comment]
Thanks for adding me as a collaborator! I'm excited to lend a hand with the project 😄

I've opened PR https://github.com/kyrylo/airbrake-rust/pull/16 which will include a development roadmap toward a stable release. Once merged, we can mark this issue as resolved.
