### ISSUE TITLE
project_id should be String

### ISSUE THREAD

**Issue by blackghost1987** [kyrylo/airbrake-rust#2]
Please modify the project_id to be a String. I am planning to use this lib with ErrBit, but it has hexadecimal project IDs so I can't set it. The ID is only used to construct the request URL as far as I know, so it should not really matter and it would make this lib more universally usable.

Thanks
Sándor

**Comment by kyrylo** [comment]
Sounds good. I'll work on this change.

P.S. This library is super new so it is very basic at the moment. I'm planning to improve it, but I wouldn't rely much on it as of now. Cheers!

**Comment by blackghost1987** [comment]
Great, thanks! Yes, I know it's very basic, but it's not a problem. I actually started to write something similiar, but haven't really finished it, so good to have something that's working at least. Hopefully it will become something to rely on, and I'm glad to help :)

**Comment by kyrylo** [comment]
Fixed by https://github.com/kyrylo/airbrake-rust/pull/4.
